baseURL = 'https://excitedstate.us.kg/'
languageCode = 'zh-cn'
title = "The EXCITED State"
theme = "PaperMod"

hasCJKLanguage = true

[outputs]
    home = ["HTML", "RSS", "JSON"]

# --- 关键修复：允许在 Markdown 中使用 HTML (让友链生效) ---
[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true

[taxonomies]
    tag = "tags"
    category = "categories"

[params]
    # --- 基础外观 ---
    defaultTheme = "auto"
    ShowReadingTime = true
    ShowShareButtons = true
    ShowWordCount = true
    ShowCodeCopyButtons = true
    ShowBreadCrumbs = true
    ShowToc = true
    comments = true
    showTagsInHome = true
    busuanzi = true
    mainSections = ["posts"]
    
    # --- 个人简介模式 ---
    [params.profileMode]
        enabled = true
        title = "The EXCITED State"
        subtitle = "😜 Hi there! Welcome to my blog!" 
        imageUrl = "https://github.com/PKChemLAB.png"
        imageWidth = 330
        imageHeight = 330
    

    # --- 社交图标 ---
    [[params.socialIcons]]
        name = "github"
        url = "https://github.com/PKChemLAB"
    
    [[params.socialIcons]]
        name = "email"
        url = "mailto:1265689026@qq.com"

    [params.assets]
    favicon = "favicon.png"
    favicon16x16 = "favicon.png"
    favicon32x32 = "favicon.png"
    apple_touch_icon = "favicon.png"
    safari_pinned_tab = "favicon.png"

[menu]
    [[menu.main]]
        name = "Homepage"
        url = "/"
        weight = 1
    
    [[menu.main]]
        name = "Posts"
        url = "/posts"
        weight = 2

    [[menu.main]]
        name = "Photos"
        url = "/photos/"
        weight = 3
        
    [[menu.main]]
        name = "Archives"
        url = "/archives"
        weight = 4
        
    [[menu.main]]
        name = "Tags"
        url = "/tags"
        weight = 5
        
    [[menu.main]]
        name = "Search"
        url = "/search/"
        weight = 6

    [[menu.main]]
        name = "Notebook"
        url = "https://pkchemlab.github.io/Notes/" 
        weight = 7

    [[menu.main]]
        name = "Links"
        url = "/links"
        weight = 8
